# Generated by Django 5.1.15 on 2026-08-10 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID généré par l'application, sans lien avec l'identité réelle.", unique=True, verbose_name='Identifiant anonyme')),
                ('plateforme', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('autre', 'Autre')], default='autre', max_length=16)),
                ('version_app', models.CharField(blank=True, default='', max_length=32)),
                ('langue', models.CharField(blank=True, default='fr', max_length=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
                'ordering': ['-derniere_activite'],
            },
        ),
    ]
