# Generated by Django 5.1.15 on 2026-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('score_risque', models.PositiveSmallIntegerField(default=0, verbose_name='Score de risque (0-100)')),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='faible', max_length=16, verbose_name='Niveau de risque')),
                ('nombre_signalements', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
                ('date_dernier_signalement', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier signalement')),
                ('est_liste_blanche', models.BooleanField(default=False, verbose_name='Sur liste blanche')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Numéro',
                'verbose_name_plural': 'Numéros',
                'ordering': ['-score_risque', '-nombre_signalements'],
            },
        ),
    ]
