# Generated by Django 5.1.15 on 2026-08-10 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_categoriearnaque_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('recommandation', models.TextField(blank=True, default='')),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='suspect', max_length=16)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('appel', 'Appel'), ('lien', 'Lien / site'), ('messagerie', 'Messagerie (WhatsApp…)'), ('reseaux', 'Réseaux sociaux'), ('mixte', 'Multicanal')], default='mixte', max_length=16)),
                ('nombre_signalements', models.PositiveIntegerField(default=0)),
                ('epinglee', models.BooleanField(default=False, help_text="Remonte l'alerte en tête de liste et sur l'écran d'accueil.", verbose_name='Épinglée')),
                ('active', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='core.categoriearnaque')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-epinglee', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('resume', models.CharField(max_length=400)),
                ('points', models.JSONField(blank=True, default=list, help_text='Liste de phrases courtes affichées en puces.')),
                ('icone', models.CharField(blank=True, default='shield', max_length=40)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils', to='core.categoriearnaque')),
            ],
            options={
                'verbose_name': 'Conseil de sécurité',
                'verbose_name_plural': 'Conseils de sécurité',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
