# Generated by Django 5.1.15 on 2026-08-10 22:29

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appareils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_verification', models.CharField(choices=[('numero', 'Numéro'), ('message', 'Message'), ('lien', 'Lien'), ('appel', 'Appel entrant'), ('vigie', 'Mode Vigie')], max_length=16)),
                ('cible', models.TextField(verbose_name='Contenu ou numéro vérifié')),
                ('resume', models.CharField(blank=True, default='', max_length=160)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='faible', max_length=16)),
                ('verdict', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='appareils.appareil')),
            ],
            options={
                'verbose_name': 'Vérification',
                'verbose_name_plural': 'Vérifications',
                'ordering': ['-date_verification'],
                'indexes': [models.Index(fields=['appareil', '-date_verification'], name='historique__apparei_119fd2_idx')],
            },
        ),
    ]
