# Generated by Django 5.1.15 on 2026-08-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('numeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('numero', 'Numéro'), ('sms', 'SMS'), ('lien', 'Lien'), ('site', 'Site'), ('message', 'Message')], max_length=16, verbose_name='Type de cible')),
                ('cible', models.CharField(max_length=500, verbose_name='Cible signalée')),
                ('declarant', models.CharField(help_text='Identifiant opaque du déclarant — aucune donnée personnelle.', max_length=64, verbose_name='Déclarant (identifiant anonymisé)')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('conteste', 'Contesté'), ('rejete', 'Rejeté')], default='en_attente', max_length=16, verbose_name='Statut de modération')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='core.categoriearnaque', verbose_name='Catégorie')),
                ('numero_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='numeros.numero', verbose_name='Numéro concerné')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
