# Generated by Django 5.1.15 on 2026-08-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appareils', '0001_initial'),
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='appareil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='appareils.appareil'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='montant_perdu',
            field=models.PositiveIntegerField(blank=True, help_text='Facultatif — permet de chiffrer le préjudice des campagnes.', null=True, verbose_name='Montant perdu (FCFA)'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='reference',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='Référence'),
        ),
    ]
