# Generated by Django 5.1.15 on 2026-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArnaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fraude_financiere', 'Fraude financière'), ('phishing', 'Phishing'), ('faux_concours', 'Faux concours / faux gain'), ('faux_recrutement', 'Faux recrutement'), ('usurpation_identite', "Usurpation d'identité"), ('demande_otp_pin', 'Demande de code OTP / PIN'), ('autre', 'Autre')], max_length=32, unique=True, verbose_name='Code catégorie')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': "Catégorie d'arnaque",
                'verbose_name_plural': "Catégories d'arnaque",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ListeBlanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('organisation', models.CharField(max_length=120, verbose_name='Organisation')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='Source / justificatif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Numéro liste blanche',
                'verbose_name_plural': 'Liste blanche',
                'ordering': ['organisation', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='LogAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('numero', 'Numéro'), ('sms', 'SMS'), ('lien', 'Lien'), ('site', 'Site'), ('message', 'Message')], max_length=16)),
                ('cible', models.CharField(max_length=500, verbose_name='Cible analysée')),
                ('score_risque', models.PositiveSmallIntegerField(default=0)),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='faible', max_length=16)),
                ('indices', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='api', help_text="Canal d'origine : api, ussd, bot, extension…", max_length=32)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Log d'analyse",
                'verbose_name_plural': "Logs d'analyse",
                'ordering': ['-date_analyse'],
            },
        ),
    ]
