# Generated by Django 5.1.15 on 2026-08-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriearnaque',
            name='code',
            field=models.CharField(choices=[('fraude_financiere', 'Fraude financière'), ('phishing', 'Phishing'), ('faux_concours', 'Faux concours / faux gain'), ('faux_recrutement', 'Faux recrutement'), ('usurpation_identite', "Usurpation d'identité"), ('faux_service_client', 'Faux service client'), ('demande_otp_pin', 'Demande de code OTP / PIN'), ('autre', 'Autre')], max_length=32, unique=True, verbose_name='Code catégorie'),
        ),
    ]
