# Generated by Django 5.1.15 on 2026-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('liens_extraits', models.JSONField(blank=True, default=list)),
                ('numeros_extraits', models.JSONField(blank=True, default=list)),
                ('score_risque', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='faible', max_length=16)),
                ('indices_detectes', models.JSONField(blank=True, default=list)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message analysé',
                'verbose_name_plural': 'Messages analysés',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
