# Generated by Django 5.1.15 on 2026-08-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appareils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionVigie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_secondes', models.PositiveIntegerField(default=0)),
                ('signaux', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('suspect', 'Suspect'), ('eleve', 'Élevé')], default='faible', max_length=16)),
                ('numero', models.CharField(blank=True, default='', help_text="Numéro de l'appel, si l'utilisateur a choisi de le renseigner.", max_length=20)),
                ('date_session', models.DateTimeField(auto_now_add=True)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_vigie', to='appareils.appareil')),
            ],
            options={
                'verbose_name': 'Session Mode Vigie',
                'verbose_name_plural': 'Sessions Mode Vigie',
                'ordering': ['-date_session'],
            },
        ),
    ]
